

* **Topic 1: Create and Initialise NumPy Array**



In [3]:
# 编写代码创建一个具有10个元素的NumPy数组，数组中的元素都初始化为1

import numpy as np

array_1 = np.ones(10)
print(array_1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


* **Topic 2: Array Slicing Operation**


In [5]:
# 给定一个NumPy数组 array，编写代码获取数组中从第3个元素开始到第7个元素的子集。
import numpy as np
array_2 = np.arange(10) # note: here is arange rather than range
sub_array = array_2[2:7]
print(sub_array)


[2 3 4 5 6]


* **Topic 3: Array Mathematical Operations**


In [8]:
# 给定两个NumPy数组 array1 和 array2，编写代码计算它们的逐元素加法结果
import numpy as np
array_1 = np.arange(10)
array_2 =np.ones(10)
print(array_1 + array_2)


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


* **Topic 4: Array Shape Transformation**

In [9]:
# 给定一个形状为 (6, 4) 的NumPy数组 array，编写代码将其变换为 (12, 2) 的形状。
import numpy as np
array_0 = np.arange(24)
array_1 = array_0.reshape((6,4))
array_2 = array_1.reshape((12,2))
print(array_2)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


* **Topic 5: Count Minimum and Maximum NumPy Array Values**

In [11]:
# 给定一个NumPy数组 array，编写代码找出数组中的最小值和最大值。

import numpy as np
array = np.arange(25)
maximum = np.max(array)
minimum = np.min(array)
print(maximum)
print(minimum)

24
0
