**Topic 1: Elementwise Multiplication of NumPy Arrays**

In [2]:
# 给定两个相同形状的NumPy数组 array1 和 array2，编写代码计算它们的逐元素乘积。
import numpy as np
array_1 = np.arange(4)
array_2 = np.ones(4)
array_multiplication = array_1 * array_2
print(array_multiplication)

[0. 1. 2. 3.]


**Exercise 2: NumPy array transpose**


In [4]:
# 给定一个NumPy数组 array，形状为 (3, 4)，编写代码将其转置。

import numpy as np
array_0 = np.arange(12).reshape((3,4))
array_1 = array_0.reshape((4,3))
print(array_0)
print(array_1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [6]:
# solution 2
array_2 = array_0.T
print(array_2)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


**Exercise 3: NumPy array conditional selection**


In [9]:
# 给定一个NumPy数组 array，编写代码计算数组所有元素的总和。
import numpy as np
array_0 = np.arange(4)
total = array_0.sum()
print(total)

6


**Exercise 4: Various selection methods for NumPy arrays**

In [11]:
# 给定一个NumPy数组 array，编写代码找出数组中所有大于10的元素。
array_3 = np.array([1,2,3,4,5,11])
greater = array_3[array_3>10]
print(greater)

[11]


**Exercise 5: Mean and standard deviation of NumPy arrays**


In [13]:
# 给定一个NumPy数组 array，编写代码计算其均值和标准差。
array_0 = np.array([1,2,3,4,5,6,7])
average = np.mean(array_0)
standard_deviation = np.std(array_0)
print(average)
print(standard_deviation)

4.0
2.0


**Exercise 6: Product and sum of NumPy arrays**

In [14]:
# 给定一个NumPy数组 array，编写代码计算其累积求和（cumulative sum）
import numpy as np

array_0 = np.array([2,3,4,5,6,7])
array_sum = np.cumsum(array_0)
print(array_sum)

[ 2  5  9 14 20 27]


**Exercise 7: Different shapes array add together(broadcast)**

In [17]:
import numpy as np
array_1 = np.arange(4).reshape((-1,1))
array_2 = np.array([1,3,4])
print(array_1 + array_2)

[[1 3 4]
 [2 4 5]
 [3 5 6]
 [4 6 7]]
