**Exercise 1: NumPy array reshaping**


In [2]:
# 给定一个包含12个元素的一维NumPy数组 array，编写代码将其重塑为形状为 (3, 4) 的二维数组。
import numpy as np
array_0 = np.arange(12)
array_1 = array_0.reshape((3,4))
print(array_1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


**Exercise 2: Merging NumPy arrays**


In [4]:
# 给定两个NumPy数组 array1 和 array2，编写代码将它们沿水平方向合并。
array_1 = np.array([1,2,3,4])
array_2 = np.ones(4)
array_concat = np.concatenate((array_1, array_2)) # combine array_1, array_2 as a tuple then put in
print(array_concat)

[1. 2. 3. 4. 1. 1. 1. 1.]


**Exercise 3: Splitting NumPy arrays**

In [6]:
# 给定一个形状为 (6, 2) 的NumPy数组 array，编写代码将其分割为两个形状为 (3, 2) 的数组。
array_0 = np.arange(12).reshape((6,2))

split_arrays = np.split(array_0, 2)
print(split_arrays[0])
print(split_arrays[1])

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]


**Exercise 4: Rotating NumPy arrays**


In [7]:
# 给定一个形状为 (3, 3) 的NumPy数组 array，编写代码实现其矩阵的转置。
array_0 = np.arange(9).reshape(-1,3)
array_1 = array_0.T
print(array_1)

[[0 3 6]
 [1 4 7]
 [2 5 8]]


**Exercise 5: Summing NumPy arrays along axes**


In [9]:
# 给定一个形状为 (4, 6) 的NumPy数组 array，编写代码沿着轴0（垂直方向）求和。
array_0 = np.random.rand(4,6)
total = np.sum(array_0, axis = 0)
print(total)


[1.60568891 2.78823323 1.19508232 1.88286557 1.69253692 1.75559915]
